source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LeoMaskAnimationKit_Example', :exclusive => true do
  pod "LeoMaskAnimationKit", :path => "../"
end

target 'LeoMaskAnimationKit_Tests', :exclusive => true do
  pod "LeoMaskAnimationKit", :path => "../"

  
end
